import unittest
import sys
import scriptscreencite
from selenium import webdriver


class Test(unittest.TestCase):
    def setUp(self):
        chrome_options = webdriver.ChromeOptions()
        chrome_options.add_argument('--start-maximized')
        self.driver = webdriver.Chrome(chrome_options=chrome_options)

    def test_fullpage_screenshot(self):
        self.driver.get("https://piter-online.net/")
        scriptscreencite.fullpage_screenshot(self.driver, "C:/Users/Марина/OneDrive/Рабочий стол/релиз/пол/пк/msk.png")
        self.driver.get("https://piter-online.net/about/contacts")
        scriptscreencite.fullpage_screenshot(self.driver, "C:/Users/Марина/OneDrive/Рабочий стол/релиз/пол/пк/aboutcontacts.png")
        self.driver.get("https://piter-online.net/about/partners")
        scriptscreencite.fullpage_screenshot(self.driver, "C:/Users/Марина/OneDrive/Рабочий стол/релиз/пол/пк/partners.png")
        self.driver.get("https://piter-online.net/about/personal-data")
        scriptscreencite.fullpage_screenshot(self.driver, "C:/Users/Марина/OneDrive/Рабочий стол/релиз/пол/пк/personal-data.png")
        self.driver.get("https://piter-online.net/about/terms-of-use")
        scriptscreencite.fullpage_screenshot(self.driver, "C:/Users/Марина/OneDrive/Рабочий стол/релиз/пол/пк/terms-of-use.png")
        self.driver.get("https://piter-online.net/actions")
        scriptscreencite.fullpage_screenshot(self.driver, "C:/Users/Марина/OneDrive/Рабочий стол/релиз/пол/пк/actions.png")
        self.driver.get("https://piter-online.net/address")
        scriptscreencite.fullpage_screenshot(self.driver, "C:/Users/Марина/OneDrive/Рабочий стол/релиз/пол/пк/address.png")
        self.driver.get("https://piter-online.net/exclusive")
        scriptscreencite.fullpage_screenshot(self.driver, "C:/Users/Марина/OneDrive/Рабочий стол/релиз/пол/пк/exclusive.png")
        self.driver.get("https://piter-online.net/nomera")
        scriptscreencite.fullpage_screenshot(self.driver, "C:/Users/Марина/OneDrive/Рабочий стол/релиз/пол/пк/nomera.png")
        self.driver.get("https://piter-online.net/nomera/vip")
        scriptscreencite.fullpage_screenshot(self.driver, "C:/Users/Марина/OneDrive/Рабочий стол/релиз/пол/пк/nomeravip.png")
        self.driver.get("https://piter-online.net/nomera/nomera-8800")
        scriptscreencite.fullpage_screenshot(self.driver, "C:/Users/Марина/OneDrive/Рабочий стол/релиз/пол/пк/nomera-8800.png")
        self.driver.get("https://piter-online.net/nomera/zolotoj")
        scriptscreencite.fullpage_screenshot(self.driver, "C:/Users/Марина/OneDrive/Рабочий стол/релиз/пол/пк/nomerazolotoj.png")
        self.driver.get("https://piter-online.net/nomera/besplatnye")
        scriptscreencite.fullpage_screenshot(self.driver, "C:/Users/Марина/OneDrive/Рабочий стол/релиз/пол/пк/nomerabesplatnye.png")
        self.driver.get("https://piter-online.net/nomera/platinovyj")
        scriptscreencite.fullpage_screenshot(self.driver, "C:/Users/Марина/OneDrive/Рабочий стол/релиз/пол/пк/nomeraplatinovyj.png")
        self.driver.get("https://piter-online.net/nomera/serebrjanyj")
        scriptscreencite.fullpage_screenshot(self.driver, "C:/Users/Марина/OneDrive/Рабочий стол/релиз/пол/пк/nomeraserebrjanyj.png")
        self.driver.get("https://piter-online.net/nomera/federalnye")
        scriptscreencite.fullpage_screenshot(self.driver, "C:/Users/Марина/OneDrive/Рабочий стол/релиз/пол/пк/nomerafederalnye.png")
        self.driver.get("https://piter-online.net/nomera/bronzovyj")
        scriptscreencite.fullpage_screenshot(self.driver, "C:/Users/Марина/OneDrive/Рабочий стол/релиз/пол/пк/nomerabronzovyj.png")
        self.driver.get("https://piter-online.net/operatory/megafon/actions")
        scriptscreencite.fullpage_screenshot(self.driver, "C:/Users/Марина/OneDrive/Рабочий стол/релиз/пол/пк/operatorymegafonactions.png")
        self.driver.get("https://piter-online.net/operatory/megafon/nomera")
        scriptscreencite.fullpage_screenshot(self.driver, "C:/Users/Марина/OneDrive/Рабочий стол/релиз/пол/пк/operatorymegafonnomera.png")
        self.driver.get("https://piter-online.net/operatory/megafon/nomera/vip")
        scriptscreencite.fullpage_screenshot(self.driver, "C:/Users/Марина/OneDrive/Рабочий стол/релиз/пол/пк/operatorymegafonnomeravip.png")
        self.driver.get("https://piter-online.net/operatory/megafon/nomera/nomera-8800")
        scriptscreencite.fullpage_screenshot(self.driver, "C:/Users/Марина/OneDrive/Рабочий стол/релиз/пол/пк/operatorymegafonnomeranomera-8800.png")
        self.driver.get("https://piter-online.net/operatory/megafon/nomera/zolotoj")
        scriptscreencite.fullpage_screenshot(self.driver, "C:/Users/Марина/OneDrive/Рабочий стол/релиз/пол/пк/operatorymegafonnomerazolotoj.png")
        self.driver.get("https://piter-online.net/operatory/megafon/nomera/besplatnye")
        scriptscreencite.fullpage_screenshot(self.driver, "C:/Users/Марина/OneDrive/Рабочий стол/релиз/пол/пк/operatorymegafonnomerabesplatnye.png")
        self.driver.get("https://piter-online.net/operatory/megafon/nomera/platinovyj")
        scriptscreencite.fullpage_screenshot(self.driver, "C:/Users/Марина/OneDrive/Рабочий стол/релиз/пол/пк/operatorymegafonnomeraplatinovyj.png")
        self.driver.get("https://piter-online.net/operatory/megafon/nomera/serebrjanyj")
        scriptscreencite.fullpage_screenshot(self.driver, "C:/Users/Марина/OneDrive/Рабочий стол/релиз/пол/пк/operatorymegafonnomeraserebrjanyj.png")
        self.driver.get("https://piter-online.net/operatory/megafon/nomera/federalnye")
        scriptscreencite.fullpage_screenshot(self.driver, "C:/Users/Марина/OneDrive/Рабочий стол/релиз/пол/пк/operatorymegafonnomerafederalnye.png")
        self.driver.get("https://piter-online.net/operatory/megafon/nomera/bronzovyj")
        scriptscreencite.fullpage_screenshot(self.driver, "C:/Users/Марина/OneDrive/Рабочий стол/релиз/пол/пк/operatorymegafonnomerabronzovyj.png")
        self.driver.get("https://piter-online.net/operatory/megafon/ratesmobile")
        scriptscreencite.fullpage_screenshot(self.driver, "C:/Users/Марина/OneDrive/Рабочий стол/релиз/пол/пк/operatorymegafonratesmobile.png")
        self.driver.get("https://piter-online.net/operatory/megafon/ratesmobile/bezlimitnyj-internet")
        scriptscreencite.fullpage_screenshot(self.driver, "C:/Users/Марина/OneDrive/Рабочий стол/релиз/пол/пк/operatorymegafonratesmobilebezlimitnyj-internet.png")
        self.driver.get("https://piter-online.net/operatory/megafon/ratesmobile/mezhdunarodnye")
        scriptscreencite.fullpage_screenshot(self.driver, "C:/Users/Марина/OneDrive/Рабочий стол/релиз/пол/пк/operatorymegafonratesmobilemezhdunarodnye.png")
        self.driver.get("https://piter-online.net/operatory/megafon/ratesmobile/dlja-plansheta")
        scriptscreencite.fullpage_screenshot(self.driver, "C:/Users/Марина/OneDrive/Рабочий стол/релиз/пол/пк/operatorymegafonratesmobiledlja-plansheta.png")
        self.driver.get("https://piter-online.net/operatory/megafon/ratesmobile/dlja-modema")
        scriptscreencite.fullpage_screenshot(self.driver, "C:/Users/Марина/OneDrive/Рабочий стол/релиз/пол/пк/operatorymegafonratesmobiledlja-modema.png")
        self.driver.get("https://piter-online.net/operatory/megafon/ratesmobile/4g")
        scriptscreencite.fullpage_screenshot(self.driver, "C:/Users/Марина/OneDrive/Рабочий стол/релиз/пол/пк/operatorymegafonratesmobile4g.png")
        self.driver.get("https://piter-online.net/operatory/megafon/ratesmobile/3g")
        scriptscreencite.fullpage_screenshot(self.driver, "C:/Users/Марина/OneDrive/Рабочий стол/релиз/пол/пк/operatorymegafonratesmobile3g.png")
        self.driver.get("https://piter-online.net/operatory/megafon/ratesmobile/bezlimitnaja-svjaz")
        scriptscreencite.fullpage_screenshot(self.driver, "C:/Users/Марина/OneDrive/Рабочий стол/релиз/пол/пк/operatorymegafonratesmobilebezlimitnaja-svjaz.png")
        self.driver.get("https://piter-online.net/operatory/megafon/ratesmobile/po-rossii")
        scriptscreencite.fullpage_screenshot(self.driver, "C:/Users/Марина/OneDrive/Рабочий стол/релиз/пол/пк/operatorymegafonratesmobilepo-rossii.png")
        self.driver.get("https://piter-online.net/operatory/megafon/ratesmobile/esim")
        scriptscreencite.fullpage_screenshot(self.driver, "C:/Users/Марина/OneDrive/Рабочий стол/релиз/пол/пк/operatorymegafonratesmobileesim.png")
        self.driver.get("https://piter-online.net/operatory/megafon")
        scriptscreencite.fullpage_screenshot(self.driver, "C:/Users/Марина/OneDrive/Рабочий стол/релиз/пол/пк/operatorymegafon.png")
        self.driver.get("https://piter-online.net/operatory")
        scriptscreencite.fullpage_screenshot(self.driver, "C:/Users/Марина/OneDrive/Рабочий стол/релиз/пол/пк/operatory.png")
        self.driver.get("https://piter-online.net/orders/office")
        scriptscreencite.fullpage_screenshot(self.driver, "C:/Users/Марина/OneDrive/Рабочий стол/релиз/пол/пк/office.png")
        self.driver.get("https://piter-online.net/orders/sat")
        scriptscreencite.fullpage_screenshot(self.driver, "C:/Users/Марина/OneDrive/Рабочий стол/релиз/пол/пк/sat.png")
        self.driver.get("https://piter-online.net/orders/tohome")
        scriptscreencite.fullpage_screenshot(self.driver, "C:/Users/Марина/OneDrive/Рабочий стол/релиз/пол/пк/tohome.png")
        self.driver.get("https://piter-online.net/providers/megafon/rates/domashnij-internet")
        scriptscreencite.fullpage_screenshot(self.driver, "C:/Users/Марина/OneDrive/Рабочий стол/релиз/пол/пк/providersmegafonratesdomashnij-internet.png")
        self.driver.get("https://piter-online.net/providers/megafon/rates/internet-100-mbit")
        scriptscreencite.fullpage_screenshot(self.driver, "C:/Users/Марина/OneDrive/Рабочий стол/релиз/пол/пк/providersmegafonratesinternet-100-mbit.png")
        self.driver.get("https://piter-online.net/providers/megafon/rates/internet-300-mbit")
        scriptscreencite.fullpage_screenshot(self.driver, "C:/Users/Марина/OneDrive/Рабочий стол/релиз/пол/пк/providersmegafonratesinternet-300-mbit.png")
        self.driver.get("https://piter-online.net/providers/megafon/rates/internet-500-mbit")
        scriptscreencite.fullpage_screenshot(self.driver, "C:/Users/Марина/OneDrive/Рабочий стол/релиз/пол/пк/providersmegafonratesinternet-500-mbit.png")
        self.driver.get("https://piter-online.net/providers/megafon/rates/internet-i-mobilnaya-svyaz")
        scriptscreencite.fullpage_screenshot(self.driver, "C:/Users/Марина/OneDrive/Рабочий стол/релиз/пол/пк/providersmegafonratesinternet-i-mobilnaya-svyaz.png")
        self.driver.get("https://piter-online.net/providers/megafon/rates/internet-i-tv")
        scriptscreencite.fullpage_screenshot(self.driver, "C:/Users/Марина/OneDrive/Рабочий стол/релиз/пол/пк/providersmegafonratesinternet-i-tv.png")
        self.driver.get("https://piter-online.net/providers/megafon/rates/internet-tv-mobile")
        scriptscreencite.fullpage_screenshot(self.driver, "C:/Users/Марина/OneDrive/Рабочий стол/релиз/пол/пк/providersmegafonratesinternet-tv-mobile.png")
        self.driver.get("https://piter-online.net/providers/megafon/rates/nedorogoj-domashnij-internet")
        scriptscreencite.fullpage_screenshot(self.driver, "C:/Users/Марина/OneDrive/Рабочий стол/релиз/пол/пк/providersmegafonratesnedorogoj-domashnij-internet.png")
        self.driver.get("https://piter-online.net/providers/megafon/rates/online-kinoteatr")
        scriptscreencite.fullpage_screenshot(self.driver, "C:/Users/Марина/OneDrive/Рабочий стол/релиз/пол/пк/providersmegafonratesonline-kinoteatr.png")
        self.driver.get("https://piter-online.net/providers/megafon/rates")
        scriptscreencite.fullpage_screenshot(self.driver, "C:/Users/Марина/OneDrive/Рабочий стол/релиз/пол/пк/providersmegafonrates.png")
        self.driver.get("https://piter-online.net/providers/megafon")
        scriptscreencite.fullpage_screenshot(self.driver, "C:/Users/Марина/OneDrive/Рабочий стол/релиз/пол/пк/providersmegafon.png")
        self.driver.get("https://piter-online.net/providers")
        scriptscreencite.fullpage_screenshot(self.driver, "C:/Users/Марина/OneDrive/Рабочий стол/релиз/пол/пк/providers.png")
        self.driver.get("https://piter-online.net/rates")
        scriptscreencite.fullpage_screenshot(self.driver, "C:/Users/Марина/OneDrive/Рабочий стол/релиз/пол/пк/rates.png")
        self.driver.get("https://piter-online.net/rates/domashnij-internet")
        scriptscreencite.fullpage_screenshot(self.driver, "C:/Users/Марина/OneDrive/Рабочий стол/релиз/пол/пк/ratesdomashnij-internet.png")
        self.driver.get("https://piter-online.net/rates/internet-i-mobilnaya-svyaz")
        scriptscreencite.fullpage_screenshot(self.driver, "C:/Users/Марина/OneDrive/Рабочий стол/релиз/пол/пк/ratesinternet-i-mobilnaya-svyaz.png")
        self.driver.get("https://piter-online.net/rates/internet-tv-mobile")
        scriptscreencite.fullpage_screenshot(self.driver, "C:/Users/Марина/OneDrive/Рабочий стол/релиз/пол/пк/ratesinternet-tv-mobile.png")
        self.driver.get("https://piter-online.net/rates/internet-i-tv")
        scriptscreencite.fullpage_screenshot(self.driver, "C:/Users/Марина/OneDrive/Рабочий стол/релиз/пол/пк/ratesinternet-i-tv.png")
        self.driver.get("https://piter-online.net/rates/nedorogoj-domashnij-internet")
        scriptscreencite.fullpage_screenshot(self.driver, "C:/Users/Марина/OneDrive/Рабочий стол/релиз/пол/пк/ratesnedorogoj-domashnij-internet.png")
        self.driver.get("https://piter-online.net/rates/internet-100-mbit")
        scriptscreencite.fullpage_screenshot(self.driver, "C:/Users/Марина/OneDrive/Рабочий стол/релиз/пол/пк/ratesinternet-100-mbit.png")
        self.driver.get("https://piter-online.net/rates/internet-300-mbit")
        scriptscreencite.fullpage_screenshot(self.driver, "C:/Users/Марина/OneDrive/Рабочий стол/релиз/пол/пк/ratesinternet-300-mbit.png")
        self.driver.get("https://piter-online.net/rates/internet-500-mbit")
        scriptscreencite.fullpage_screenshot(self.driver, "C:/Users/Марина/OneDrive/Рабочий стол/релиз/пол/пк/ratesinternet-500-mbit.png")
        self.driver.get("https://piter-online.net/rates/online-kinoteatr")
        scriptscreencite.fullpage_screenshot(self.driver, "C:/Users/Марина/OneDrive/Рабочий стол/релиз/пол/пк/ratesonline-kinoteatr.png")
        self.driver.get("https://piter-online.net/ratesmobile")
        scriptscreencite.fullpage_screenshot(self.driver, "C:/Users/Марина/OneDrive/Рабочий стол/релиз/пол/пк/ratesmobile.png")
        self.driver.get("https://piter-online.net/ratesmobile/dlja-noutbuka")
        scriptscreencite.fullpage_screenshot(self.driver, "C:/Users/Марина/OneDrive/Рабочий стол/релиз/пол/пк/ratesmobiledlja-noutbuka.png")
        self.driver.get("https://piter-online.net/ratesmobile/bezlimitnaja-svjaz")
        scriptscreencite.fullpage_screenshot(self.driver, "C:/Users/Марина/OneDrive/Рабочий стол/релиз/пол/пк/ratesmobilebezlimitnaja-svjaz.png")
        self.driver.get("https://piter-online.net/ratesmobile/3g")
        scriptscreencite.fullpage_screenshot(self.driver, "C:/Users/Марина/OneDrive/Рабочий стол/релиз/пол/пк/ratesmobile3g.png")
        self.driver.get("https://piter-online.net/ratesmobile/perenos_nomera")
        scriptscreencite.fullpage_screenshot(self.driver, "C:/Users/Марина/OneDrive/Рабочий стол/релиз/пол/пк/ratesmobileperenos_nomera.png")
        self.driver.get("https://piter-online.net/ratesmobile/4g")
        scriptscreencite.fullpage_screenshot(self.driver, "C:/Users/Марина/OneDrive/Рабочий стол/релиз/пол/пк/ratesmobile4g.png")
        self.driver.get("https://piter-online.net/ratesmobile/vygodnye")
        scriptscreencite.fullpage_screenshot(self.driver, "C:/Users/Марина/OneDrive/Рабочий стол/релиз/пол/пк/ratesmobilevygodnye.png")
        self.driver.get("https://piter-online.net/ratesmobile/po-rossii")
        scriptscreencite.fullpage_screenshot(self.driver, "C:/Users/Марина/OneDrive/Рабочий стол/релиз/пол/пк/ratesmobilepo-rossii.png")
        self.driver.get("https://piter-online.net/ratesmobile/esim")
        scriptscreencite.fullpage_screenshot(self.driver, "C:/Users/Марина/OneDrive/Рабочий стол/релиз/пол/пк/ratesmobileesim.png")
        self.driver.get("https://piter-online.net/ratesmobile/dlja-modema")
        scriptscreencite.fullpage_screenshot(self.driver, "C:/Users/Марина/OneDrive/Рабочий стол/релиз/пол/пк/ratesmobiledlja-modema.png")
        self.driver.get("https://piter-online.net/ratesmobile/dlja-plansheta")
        scriptscreencite.fullpage_screenshot(self.driver, "C:/Users/Марина/OneDrive/Рабочий стол/релиз/пол/пк/ratesmobiledlja-plansheta.png")
        self.driver.get("https://piter-online.net/ratesmobile/mezhdunarodnye")
        scriptscreencite.fullpage_screenshot(self.driver, "C:/Users/Марина/OneDrive/Рабочий стол/релиз/пол/пк/ratesmobilemezhdunarodnye.png")
        self.driver.get("https://piter-online.net/ratesmobile/bezlimitnyj-internet")
        scriptscreencite.fullpage_screenshot(self.driver, "C:/Users/Марина/OneDrive/Рабочий стол/релиз/пол/пк/ratesmobilebezlimitnyj-internet.png")
        self.driver.get("https://piter-online.net/rates/internet-i-mobilnaya-svyaz")
        scriptscreencite.fullpage_screenshot(self.driver, "C:/Users/Марина/OneDrive/Рабочий стол/релиз/пол/пк/ratesinternet-i-mobilnaya-svyaz.png")
        self.driver.get("https://piter-online.net/rates/internet-tv-mobile")
        scriptscreencite.fullpage_screenshot(self.driver, "C:/Users/Марина/OneDrive/Рабочий стол/релиз/пол/пк/ratesinternet-tv-mobile.png")
        self.driver.get("https://piter-online.net/rating")
        scriptscreencite.fullpage_screenshot(self.driver, "C:/Users/Марина/OneDrive/Рабочий стол/релиз/пол/пк/rating.png")
        self.driver.get("https://piter-online.net/reviews")
        scriptscreencite.fullpage_screenshot(self.driver, "C:/Users/Марина/OneDrive/Рабочий стол/релиз/пол/пк/reviews.png")


if __name__ == "__main__":
    unittest.main(argv=[sys.argv[0]])