import unittest
import sys
import scriptscreencite
from selenium import webdriver


class Test(unittest.TestCase):
    def setUp(self):
        chrome_options = webdriver.ChromeOptions()
        chrome_options.add_argument('--start-maximized')
        self.driver = webdriver.Chrome(chrome_options=chrome_options)

    def test_fullpage_screenshot(self):
        self.driver.get("https://101internet.ru/ekaterinburg/about/contacts")
        scriptscreencite.fullpage_screenshot(self.driver, "C:/Users/Марина/OneDrive/Рабочий стол/релиз/101/пк/contacts.png")
        self.driver.get("https://101internet.ru/ekaterinburg/about/partners")
        scriptscreencite.fullpage_screenshot(self.driver, "C:/Users/Марина/OneDrive/Рабочий стол/релиз/101/пк/partners.png")
        self.driver.get("https://101internet.ru/ekaterinburg/about/terms-of-use")
        scriptscreencite.fullpage_screenshot(self.driver, "C:/Users/Марина/OneDrive/Рабочий стол/релиз/101/пк/terms-of-use.png")
        self.driver.get("https://101internet.ru/ekaterinburg/actions")
        scriptscreencite.fullpage_screenshot(self.driver, "C:/Users/Марина/OneDrive/Рабочий стол/релиз/101/пк/actions.png")
        self.driver.get("https://101internet.ru/ekaterinburg/address")
        scriptscreencite.fullpage_screenshot(self.driver, "C:/Users/Марина/OneDrive/Рабочий стол/релиз/101/пк/address.png")
        self.driver.get("https://101internet.ru/ekaterinburg/exclusive")
        scriptscreencite.fullpage_screenshot(self.driver, "C:/Users/Марина/OneDrive/Рабочий стол/релиз/101/пк/exclusive.png")
        self.driver.get("https://101internet.ru/ekaterinburg/nomera")
        scriptscreencite.fullpage_screenshot(self.driver, "C:/Users/Марина/OneDrive/Рабочий стол/релиз/101/пк/nomera.png")
        self.driver.get("https://101internet.ru/ekaterinburg/nomera/bronzovyj")
        scriptscreencite.fullpage_screenshot(self.driver, "C:/Users/Марина/OneDrive/Рабочий стол/релиз/101/пк/nomerabronzovyj.png")
        self.driver.get("https://101internet.ru/ekaterinburg/nomera/serebrjanyj")
        scriptscreencite.fullpage_screenshot(self.driver, "C:/Users/Марина/OneDrive/Рабочий стол/релиз/101/пк/nomeraserebrjanyj.png")
        self.driver.get("https://101internet.ru/ekaterinburg/nomera/besplatnye")
        scriptscreencite.fullpage_screenshot(self.driver, "C:/Users/Марина/OneDrive/Рабочий стол/релиз/101/пк/nomerabesplatnye.png")
        self.driver.get("https://101internet.ru/ekaterinburg/operatory/megafon/actions")
        scriptscreencite.fullpage_screenshot(self.driver, "C:/Users/Марина/OneDrive/Рабочий стол/релиз/101/пк/operatorymegafonactions.png")
        self.driver.get("https://101internet.ru/ekaterinburg/providers/megafon/rates/internet-tv-mobile")
        scriptscreencite.fullpage_screenshot(self.driver, "C:/Users/Марина/OneDrive/Рабочий стол/релиз/101/пк/rates3v1.png")
        self.driver.get("https://101internet.ru/ekaterinburg/operatory/megafon/nomera")
        scriptscreencite.fullpage_screenshot(self.driver, "C:/Users/Марина/OneDrive/Рабочий стол/релиз/101/пк/operatorymegafonnomera.png")
        self.driver.get("https://101internet.ru/ekaterinburg/operatory/megafon/nomera/besplatnye")
        scriptscreencite.fullpage_screenshot(self.driver, "C:/Users/Марина/OneDrive/Рабочий стол/релиз/101/пк/operatorymegafonnomerabesplatnye.png")
        self.driver.get("https://101internet.ru/ekaterinburg/operatory/megafon/ratesmobile")
        scriptscreencite.fullpage_screenshot(self.driver, "C:/Users/Марина/OneDrive/Рабочий стол/релиз/101/пк/operatorymegafonratesmobile.png")
        self.driver.get("https://101internet.ru/ekaterinburg/operatory/megafon/ratesmobile/bezlimitnyj-internet")
        scriptscreencite.fullpage_screenshot(self.driver, "C:/Users/Марина/OneDrive/Рабочий стол/релиз/101/пк/operatorymegafonratesmobilebezlimitnyj-internet.png")
        self.driver.get("https://101internet.ru/ekaterinburg/operatory/megafon/ratesmobile/mezhdunarodnye")
        scriptscreencite.fullpage_screenshot(self.driver, "C:/Users/Марина/OneDrive/Рабочий стол/релиз/101/пк/operatorymegafonratesmobilemezhdunarodnye.png")
        self.driver.get("https://101internet.ru/ekaterinburg/operatory/megafon/ratesmobile/dlja-plansheta")
        scriptscreencite.fullpage_screenshot(self.driver, "C:/Users/Марина/OneDrive/Рабочий стол/релиз/101/пк/operatorymegafonratesmobiledlja-plansheta.png")
        self.driver.get("https://101internet.ru/ekaterinburg/operatory/megafon/ratesmobile/dlja-modema")
        scriptscreencite.fullpage_screenshot(self.driver, "C:/Users/Марина/OneDrive/Рабочий стол/релиз/101/пк/operatorymegafonratesmobiledlja-modema.png")
        self.driver.get("https://101internet.ru/ekaterinburg/operatory/megafon/ratesmobile/4g")
        scriptscreencite.fullpage_screenshot(self.driver, "C:/Users/Марина/OneDrive/Рабочий стол/релиз/101/пк/operatorymegafonratesmobile4g.png")
        self.driver.get("https://101internet.ru/ekaterinburg/operatory/megafon/ratesmobile/3g")
        scriptscreencite.fullpage_screenshot(self.driver, "C:/Users/Марина/OneDrive/Рабочий стол/релиз/101/пк/operatorymegafonratesmobile3g.png")
        self.driver.get("https://101internet.ru/ekaterinburg/operatory/megafon/ratesmobile/bezlimitnaja-svjaz")
        scriptscreencite.fullpage_screenshot(self.driver, "C:/Users/Марина/OneDrive/Рабочий стол/релиз/101/пк/operatorymegafonratesmobilebezlimitnaja-svjaz.png")
        self.driver.get("https://101internet.ru/ekaterinburg/operatory/megafon/ratesmobile/po-rossii")
        scriptscreencite.fullpage_screenshot(self.driver, "C:/Users/Марина/OneDrive/Рабочий стол/релиз/101/пк/operatorymegafonratesmobilepo-rossii.png")
        self.driver.get("https://101internet.ru/ekaterinburg/operatory/megafon/ratesmobile/esim")
        scriptscreencite.fullpage_screenshot(self.driver, "C:/Users/Марина/OneDrive/Рабочий стол/релиз/101/пк/operatorymegafonratesmobileesim.png")
        self.driver.get("https://101internet.ru/ekaterinburg/operatory/megafon")
        scriptscreencite.fullpage_screenshot(self.driver, "C:/Users/Марина/OneDrive/Рабочий стол/релиз/101/пк/operatorymegafon.png")
        self.driver.get("https://101internet.ru/ekaterinburg/operatory")
        scriptscreencite.fullpage_screenshot(self.driver, "C:/Users/Марина/OneDrive/Рабочий стол/релиз/101/пк/operatory.png")
        self.driver.get("https://101internet.ru/ekaterinburg/orders/home?tariff_id=100647001")
        scriptscreencite.fullpage_screenshot(self.driver, "C:/Users/Марина/OneDrive/Рабочий стол/релиз/101/пк/zayavkanapodkl.png")
        self.driver.get("https://101internet.ru/ekaterinburg/orders/office")
        scriptscreencite.fullpage_screenshot(self.driver, "C:/Users/Марина/OneDrive/Рабочий стол/релиз/101/пк/ordersoffice.png")
        self.driver.get("https://101internet.ru/ekaterinburg/orders/sat")
        scriptscreencite.fullpage_screenshot(self.driver, "C:/Users/Марина/OneDrive/Рабочий стол/релиз/101/пк/orderssat.png")
        self.driver.get("https://101internet.ru/ekaterinburg/orders/tohome")
        scriptscreencite.fullpage_screenshot(self.driver, "C:/Users/Марина/OneDrive/Рабочий стол/релиз/101/пк/orderstohome.png")
        self.driver.get("https://101internet.ru/ekaterinburg/providers/actions/rostelecom")
        scriptscreencite.fullpage_screenshot(self.driver, "C:/Users/Марина/OneDrive/Рабочий стол/релиз/101/пк/providersactionsrostelecom.png")
        self.driver.get("https://101internet.ru/ekaterinburg/providers/rostelecom/rates")
        scriptscreencite.fullpage_screenshot(self.driver, "C:/Users/Марина/OneDrive/Рабочий стол/релиз/101/пк/providersrostelecomrates.png")
        self.driver.get("https://101internet.ru/ekaterinburg/providers/rostelecom/rates/internet-i-mobilnaya-svyaz")
        scriptscreencite.fullpage_screenshot(self.driver, "C:/Users/Марина/OneDrive/Рабочий стол/релиз/101/пк/providersrostelecomratesinternet-i-mobilnaya-svyaz.png")
        self.driver.get("https://101internet.ru/ekaterinburg/providers/rostelecom/rates/internet-tv-mobile")
        scriptscreencite.fullpage_screenshot(self.driver, "C:/Users/Марина/OneDrive/Рабочий стол/релиз/101/пк/providersrostelecomratesinternet-tv-mobile.png")
        self.driver.get("https://101internet.ru/ekaterinburg/providers/rostelecom/rates/domashnij-internet")
        scriptscreencite.fullpage_screenshot(self.driver, "C:/Users/Марина/OneDrive/Рабочий стол/релиз/101/пк/providersrostelecomratesdomashnij-internet.png")
        self.driver.get("https://101internet.ru/ekaterinburg/providers/rostelecom/rates/internet-i-tv")
        scriptscreencite.fullpage_screenshot(self.driver, "C:/Users/Марина/OneDrive/Рабочий стол/релиз/101/пк/providersrostelecomratesinternet-i-tv.png")
        self.driver.get("https://101internet.ru/ekaterinburg/providers/rostelecom/rates/nedorogoj-domashnij-internet")
        scriptscreencite.fullpage_screenshot(self.driver, "C:/Users/Марина/OneDrive/Рабочий стол/релиз/101/пк/providersrostelecomratesnedorogoj-domashnij-internet.png")
        self.driver.get("https://101internet.ru/ekaterinburg/providers/rostelecom/rates/internet-100-mbit")
        scriptscreencite.fullpage_screenshot(self.driver, "C:/Users/Марина/OneDrive/Рабочий стол/релиз/101/пк/providersrostelecomratesinternet-100-mbit.png")
        self.driver.get("https://101internet.ru/ekaterinburg/providers/rostelecom/rates/internet-500-mbit")
        scriptscreencite.fullpage_screenshot(self.driver, "C:/Users/Марина/OneDrive/Рабочий стол/релиз/101/пк/providersrostelecomratesinternet-500-mbit.png")
        self.driver.get("https://101internet.ru/ekaterinburg/providers/rostelecom/rates/online-kinoteatr")
        scriptscreencite.fullpage_screenshot(self.driver, "C:/Users/Марина/OneDrive/Рабочий стол/релиз/101/пк/providersrostelecomratesonline-kinoteatr.png")
        self.driver.get("https://101internet.ru/ekaterinburg/providers/rostelecom")
        scriptscreencite.fullpage_screenshot(self.driver, "C:/Users/Марина/OneDrive/Рабочий стол/релиз/101/пк/providersrostelecom.png")
        self.driver.get("https://101internet.ru/ekaterinburg/providers")
        scriptscreencite.fullpage_screenshot(self.driver, "C:/Users/Марина/OneDrive/Рабочий стол/релиз/101/пк/providers.png")
        self.driver.get("https://101internet.ru/ekaterinburg/rates?house_id=228947")
        scriptscreencite.fullpage_screenshot(self.driver, "C:/Users/Марина/OneDrive/Рабочий стол/релиз/101/пк/rateshouse_id=228947.png")
        self.driver.get("https://101internet.ru/ekaterinburg/rates?house_id=228947&filter=domashniy-internet.png")
        scriptscreencite.fullpage_screenshot(self.driver, "C:/Users/Марина/OneDrive/Рабочий стол/релиз/101/пк/rateshouse_id=228947&filter=domashniy-internet.png")
        self.driver.get("https://101internet.ru/ekaterinburg/rates?filter=internetAndTV&house_id=228947")
        scriptscreencite.fullpage_screenshot(self.driver, "C:/Users/Марина/OneDrive/Рабочий стол/релиз/101/пк/ratesfilter=internetAndTV&house_id=228947.png")
        self.driver.get("https://101internet.ru/ekaterinburg/rates?filter=onlyTV&house_id=228947")
        scriptscreencite.fullpage_screenshot(self.driver, "C:/Users/Марина/OneDrive/Рабочий стол/релиз/101/пк/ratesfilter=onlyTV&house_id=228947.png")
        self.driver.get("https://101internet.ru/ekaterinburg/rates?filter=bezlimitniy-intenet&house_id=228947")
        scriptscreencite.fullpage_screenshot(self.driver, "C:/Users/Марина/OneDrive/Рабочий стол/релиз/101/пк/ratesfilter=bezlimitniy-intenet&house_id=228947.png")
        self.driver.get("https://101internet.ru/ekaterinburg/rates?filter=mobile&house_id=228947")
        scriptscreencite.fullpage_screenshot(self.driver, "C:/Users/Марина/OneDrive/Рабочий стол/релиз/101/пк/ratesfilter=mobile&house_id=228947.png")
        self.driver.get("https://101internet.ru/ekaterinburg/rates/domashnij-internet")
        scriptscreencite.fullpage_screenshot(self.driver, "C:/Users/Марина/OneDrive/Рабочий стол/релиз/101/пк/ratesdomashnij-internet.png")
        self.driver.get("https://101internet.ru/ekaterinburg/rates/internet-i-mobilnaya-svyaz")
        scriptscreencite.fullpage_screenshot(self.driver, "C:/Users/Марина/OneDrive/Рабочий стол/релиз/101/пк/ratesinternet-i-mobilnaya-svyaz.png")
        self.driver.get("https://101internet.ru/ekaterinburg/rates/internet-tv-mobile")
        scriptscreencite.fullpage_screenshot(self.driver, "C:/Users/Марина/OneDrive/Рабочий стол/релиз/101/пк/ratesinternet-tv-mobile.png")
        self.driver.get("https://101internet.ru/ekaterinburg/rates/internet-i-tv")
        scriptscreencite.fullpage_screenshot(self.driver, "C:/Users/Марина/OneDrive/Рабочий стол/релиз/101/пк/ratesinternet-i-tv.png")
        self.driver.get("https://101internet.ru/ekaterinburg/rates/nedorogoj-domashnij-internet")
        scriptscreencite.fullpage_screenshot(self.driver, "C:/Users/Марина/OneDrive/Рабочий стол/релиз/101/пк/ratesnedorogoj-domashnij-internet.png")
        self.driver.get("https://101internet.ru/ekaterinburg/rates/internet-100-mbit")
        scriptscreencite.fullpage_screenshot(self.driver, "C:/Users/Марина/OneDrive/Рабочий стол/релиз/101/пк/ratesinternet-100-mbit.png")
        self.driver.get("https://101internet.ru/ekaterinburg/rates/internet-500-mbit")
        scriptscreencite.fullpage_screenshot(self.driver, "C:/Users/Марина/OneDrive/Рабочий стол/релиз/101/пк/ratesinternet-500-mbit.png")
        self.driver.get("https://101internet.ru/ekaterinburg/rates/online-kinoteatr")
        scriptscreencite.fullpage_screenshot(self.driver, "C:/Users/Марина/OneDrive/Рабочий стол/релиз/101/пк/ratesonline-kinoteatr.png")
        self.driver.get("https://101internet.ru/ekaterinburg/ratesmobile")
        scriptscreencite.fullpage_screenshot(self.driver, "C:/Users/Марина/OneDrive/Рабочий стол/релиз/101/пк/ratesmobile.png")
        self.driver.get("https://101internet.ru/ekaterinburg/ratesmobile/dlja-noutbuka")
        scriptscreencite.fullpage_screenshot(self.driver, "C:/Users/Марина/OneDrive/Рабочий стол/релиз/101/пк/ratesmobiledlja-noutbuka.png")
        self.driver.get("https://101internet.ru/ekaterinburg/ratesmobile/bezlimitnaja-svjaz")
        scriptscreencite.fullpage_screenshot(self.driver, "C:/Users/Марина/OneDrive/Рабочий стол/релиз/101/пк/ratesmobilebezlimitnaja-svjaz.png")
        self.driver.get("https://101internet.ru/ekaterinburg/ratesmobile/3g")
        scriptscreencite.fullpage_screenshot(self.driver, "C:/Users/Марина/OneDrive/Рабочий стол/релиз/101/пк/ratesmobile3g.png")
        self.driver.get("https://101internet.ru/ekaterinburg/ratesmobile/perenos_nomera")
        scriptscreencite.fullpage_screenshot(self.driver, "C:/Users/Марина/OneDrive/Рабочий стол/релиз/101/пк/ratesmobileperenos_nomera.png")
        self.driver.get("https://101internet.ru/ekaterinburg/ratesmobile/4g")
        scriptscreencite.fullpage_screenshot(self.driver, "C:/Users/Марина/OneDrive/Рабочий стол/релиз/101/пк/ratesmobile4g.png")
        self.driver.get("https://101internet.ru/ekaterinburg/ratesmobile/vygodnye")
        scriptscreencite.fullpage_screenshot(self.driver, "C:/Users/Марина/OneDrive/Рабочий стол/релиз/101/пк/ratesmobilevygodnye.png")
        self.driver.get("https://101internet.ru/ekaterinburg/ratesmobile/po-rossii")
        scriptscreencite.fullpage_screenshot(self.driver, "C:/Users/Марина/OneDrive/Рабочий стол/релиз/101/пк/ratesmobilepo-rossii.png")
        self.driver.get("https://101internet.ru/ekaterinburg/ratesmobile/esim")
        scriptscreencite.fullpage_screenshot(self.driver, "C:/Users/Марина/OneDrive/Рабочий стол/релиз/101/пк/ratesmobileesim.png")
        self.driver.get("https://101internet.ru/ekaterinburg/ratesmobile/dlja-modema")
        scriptscreencite.fullpage_screenshot(self.driver, "C:/Users/Марина/OneDrive/Рабочий стол/релиз/101/пк/ratesmobiledlja-modema.png")
        self.driver.get("https://101internet.ru/ekaterinburg/ratesmobile/dlja-plansheta")
        scriptscreencite.fullpage_screenshot(self.driver, "C:/Users/Марина/OneDrive/Рабочий стол/релиз/101/пк/ratesmobiledlja-plansheta.png")
        self.driver.get("https://101internet.ru/ekaterinburg/ratesmobile/mezhdunarodnye")
        scriptscreencite.fullpage_screenshot(self.driver, "C:/Users/Марина/OneDrive/Рабочий стол/релиз/101/пк/ratesmobilemezhdunarodnye.png")
        self.driver.get("https://101internet.ru/ekaterinburg/ratesmobile/bezlimitnyj-internet")
        scriptscreencite.fullpage_screenshot(self.driver, "C:/Users/Марина/OneDrive/Рабочий стол/релиз/101/пк/ratesmobilebezlimitnyj-internet.png")
        self.driver.get("https://101internet.ru/ekaterinburg/rates/internet-i-mobilnaya-svyaz")
        scriptscreencite.fullpage_screenshot(self.driver, "C:/Users/Марина/OneDrive/Рабочий стол/релиз/101/пк/ratesinternet-i-mobilnaya-svyaz.png")
        self.driver.get("https://101internet.ru/ekaterinburg/rates/internet-tv-mobile")
        scriptscreencite.fullpage_screenshot(self.driver, "C:/Users/Марина/OneDrive/Рабочий стол/релиз/101/пк/ratesinternet-tv-mobile.png")
        self.driver.get("https://101internet.ru/ekaterinburg/rating/rostelecom")
        scriptscreencite.fullpage_screenshot(self.driver, "C:/Users/Марина/OneDrive/Рабочий стол/релиз/101/пк/ratingrostelecom.png")
        self.driver.get("https://101internet.ru/ekaterinburg/rating")
        scriptscreencite.fullpage_screenshot(self.driver, "C:/Users/Марина/OneDrive/Рабочий стол/релиз/101/пк/rating.png")
        self.driver.get("https://101internet.ru/ekaterinburg/reviews")
        scriptscreencite.fullpage_screenshot(self.driver, "C:/Users/Марина/OneDrive/Рабочий стол/релиз/101/пк/reviews.png")
        self.driver.get("https://101internet.ru/ekaterinburg")
        scriptscreencite.fullpage_screenshot(self.driver, "C:/Users/Марина/OneDrive/Рабочий стол/релиз/101/пк/ekaterinburg.png")


if __name__ == "__main__":
    unittest.main(argv=[sys.argv[0]])